### ISSUE TITLE
Alternative to Google Stackdriver

### ISSUE THREAD

**Issue by suancarloj** [harlow/go-micro-services#23]
Hello,

I was following the readme and tried to get a trial account for Google Stackdriver, sadly they restricted the service to companies only here in Europe, I currently don't have one. Could it be possible to offer/suggest an alternatives ?

Thank you very much :)

**Comment by harlow** [comment]
Hi @suancarloj thanks for the note. I've removed the Stackdriver dep as it seems to be tripping a few people up when trying to run the demo code.

I'll need to investigate if there is anything that is easy to run locally (maybe Zipkin w/ Opentracing?), but ideally wouldn't be a requirement for people who just want to clone and run the code.

Will leave the issue open for time being, but don't have a good answer to this one atm.
