### ISSUE TITLE
Any example for using service discovery (e.g. consul) with this code?

### ISSUE THREAD

**Issue by rcholic** [harlow/go-micro-services#24]
From my understanding, the current design does not use service discovery, instead each service is deployed in a single docker container. I was wondering how to integrate consul into this implementation, and how to run multiple instances for each service. 

Thanks

**Comment by harlow** [comment]
great question. haven't used consul before so maybe i'll spike something out when i have some free time and see if it feels like a good fit for this repo

**Comment by harlow** [comment]
>  I was wondering how to integrate consul into this implementation, and how to run multiple instances for each service.

this i'm not sure about... Looks like some load balancing will be needed: https://grpc.io/blog/loadbalancing
https://github.com/grpc/grpc/blob/master/doc/load-balancing.md

**Comment by harlow** [comment]
closing consul issue, added new issue for load balancing: https://github.com/harlow/go-micro-services/issues/26
