### ISSUE TITLE
access microservices

### ISSUE THREAD

**Issue by Fatahir** [harlow/go-micro-services#34]
how we access multiple microservices?

**Comment by harlow** [comment]
Hi, not sure I understand the question. Can you elaborate?

**Comment by Fatahir** [comment]
yes sure, you have implemented different services in your code like frontend, jaeger, geo, rate, search, profile. Frontend service is accessed by localhost:5000. Similarly if we have to search hotel within specified date then it is accessed by localhost:5000/hotels?inDate=2015-04-09&outDate=2015-04-10. My question is how I access other services like profile, rate, ...

**Comment by harlow** [comment]
> My question is how I access other services like profile, rate, 

You will need to access those via GRPC connection. They have docker-compose links instead of specific ports:
https://github.com/harlow/go-micro-services/blob/master/docker-compose.yml#L8-L11
