### ISSUE TITLE
Question about the GRPC protoc version

### ISSUE THREAD

**Issue by ZhixinLai** [harlow/go-micro-services#37]
Hi, I wanna convert the .proto file to the .pb.go file, but use the latest protoc version of 3.6.1, but generate a totally different .pb.go file with your original .proto file.

**Comment by ZhixinLai** [comment]
could you please tell me which version of protobuf you are using? Thanks~

**Comment by harlow** [comment]
@ZhixinLai thanks for creating the issue. I'm using `3.15.8`. I updated the go_output to point correctly at the proto dir. Hopefully this helps

```
$ protoc --version
libprotoc 3.15.8
```
