### ISSUE TITLE
grpc dialer issue

### ISSUE THREAD

**Issue by lepidopterane-atsmith** [harlow/go-micro-services#40]
Hi,
      I'm running a [DeathStarBench application](https://github.com/delimitrou/DeathStarBench/tree/master/hotelReservation) built on top of this project. Or, at least I'm trying to. I have been trying to run all of this with Docker Compose in Ubuntu, but I keep hitting this dependency error that seems like more of an issue with this project than with DeathStarBench and I don't know what I'd like to do. I'll also mention this is part of PhD research I'm doing at Tufts University. Anyway, here's the error:

```
go: finding module for package google.golang.org/grpc/naming
go: downloading google.golang.org/grpc v1.46.0
github.com/harlow/go-micro-services/dialer imports github.com/olivere/grpc/lb/consul imports
	google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.46.0), but does not contain package google.golang.org/grpc/naming
The command '/bin/sh -c go mod vendor' returned a non-zero code: 1
ERROR: Service 'frontend' failed to build : Build failed
```

**Comment by harlow** [comment]
I can't replicate the issue locally (MacOS) but my assumption is one of the dependencies around grpc libraries has changed. It's also possible that DeathStarBench (I'm not familiar with project) has an older copy of the codebase?
