### ISSUE TITLE
Use database instead of data binding from JSON

### ISSUE THREAD

**Issue by tiennampham23** [harlow/go-micro-services#41]
Hi @harlow, I want to contribute this project with use Database instead of binding data from JSON files. Is this make senses?

**Comment by harlow** [comment]
@tiennampham23 great idea! do you have any particular database in mind? Something that uses the sql db driver would be neat.

Things that are important for me:
1. users can easily bootstrap this app (top goal)
2. the DBs are stored as flat file(s) in the repo (easy to inspect).. SQLite could be great for this

**Comment by tiennampham23** [comment]
@harlow yes, I think I will use SQLite and write code as abstraction to reuse with other SQL Database, thank you

**Comment by harlow** [comment]
Perfect!

**Comment by harlow** [comment]
closing this for now, if there is any interest in a JSON DB in the future I can help
